### ISSUE TITLE
no installation instructions

### ISSUE THREAD

**Issue by zevaverbach** [Down10/Confectio#1]

**Comment by Down10** [comment]
what are you doing here?! lol

**Comment by zevaverbach** [comment]
forking yr repos, mang

**Comment by zevaverbach** [comment]
i like these themes -- considered making Jetbrains-compatible versions?

**Comment by Down10** [comment]
Confectio is kind of a side project, and not really ready for prime time. I tried to push it to the Atom theme repo and it never worked, so I kind of left it at that.

I'd be happy to extend it to other platforms if it gained some traction on one.
